# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Image Machine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Image Machine


  target 'Image MachineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Image MachineUITests' do
    # Pods for testing
  end

end
